


GET http://localhost:9000

#####

POST http://localhost:9000/books
Content-Type: application/json

{
  "name": "Test Book",
  "year": 2022,
  "author": "Test Author",
  "summary": "This is a test book.",
  "publisher": "Test Publisher",
  "pageCount": 200,
  "readPage": 50,
  "reading": true
}
####
GET http://localhost:9000/books

####
GET http://localhost:9000/books/132

###
GET http://localhost:9000/books/NB_PHl63QUcGiunHskpzU

###
DELETE  http://localhost:9000/books/12

####
DELETE http://localhost:9000/books/NB_PHl63QUcGiunHskpzU